version: '3.8'
services:
  generate-certificates:
    image: "elasticsearch:${ELASTIC_VERSION}"
    working_dir: /playbooks
    volumes:
      - .:/playbooks
    command: [ "/bin/sh", "-c", "scripts/generate-certs.sh $$CERTS_DIR $$CERTS_CONFIG" ]

  run-elasticsearch-stress-test:
    image: "basnik/elasticsearch-stress-test:latest"
    working_dir: /playbooks
    volumes:
      - .:/playbooks
    command: [ "/bin/sh", "-c", "scripts/run-elasticsearch-stress-test.sh $$ES_URL $$CA_CERT_PATH $$USERNAME $$PASSWORD" ]