---
- set_fact:
    node_exporter_version_local_fact: "1.1.2"
    node_exporter_checksum_local_fact: "8c1f6a317457a658e0ae68ad710f6b4098db2cad10204649b51e3c043aa3e70d"
    architecture_local_fact: "amd64"

- name: echo url
  debug:
    msg: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version_local_fact }}/node_exporter-{{ node_exporter_version_local_fact }}.linux-{{ architecture_local_fact }}.tar.gz"

- name: Install node exporter
  block:
    - name: Download node_exporter binary to local folder
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version_local_fact }}/node_exporter-{{ node_exporter_version_local_fact }}.linux-{{ architecture_local_fact }}.tar.gz"
        dest: "/tmp/node_exporter-{{ node_exporter_version_local_fact }}.linux-{{ architecture_local_fact }}.tar.gz"
        checksum: "sha256:{{ node_exporter_checksum_local_fact }}"
        validate_certs: false
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack node_exporter binary
      unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version_local_fact }}.linux-{{ architecture_local_fact }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/node_exporter-{{ node_exporter_version_local_fact }}.linux-{{ architecture_local_fact }}/node_exporter"
      delegate_to: localhost
      check_mode: false

    - include_role:
        name: ansible-node-exporter
      vars:
        node_exporter_version: "{{ node_exporter_version_local_fact }}"
        node_exporter_binary_local_dir: "/tmp/node_exporter-{{ node_exporter_version_local_fact }}.linux-{{ architecture_local_fact }}/"
