---

- name: Prerequisite for metricbeat installation
  tags: [ 'copy_ca','install_metricbeat' ]
  block:
    - name: Setup Directories and copy certificates that are required for metricbeat
      include_tasks: copy-dertificates.yml

- name: Install and Configure metricbeat
  become: yes
  tags: [ 'install_metricbeat' ]
  block:
    - include_role:
        name: ansible-beats
      vars:
        beat: "metricbeat"
        beats_version: "{{ metricbeat_version }}"
        version_lock: true
        restart_on_change: true
        beat_conf:
          metricbeat.modules:
            - "{{ metricbeat_module }}"
          metricbeat.max_start_delay: 20s
          timeseries.enabled: true
          setup:
            ilm:
              enabled: true
              policy_name: manage-monitoring-logs
              rollover_alias: "metricbeat-logs"
              pattern: "000001"
              overwrite: true
              policy_file: /etc/metricbeat/policies/ilm_policy.json
        #            kibana:
        #              host: "http://10.0.0.11:5601"
        #              protocol: http
        #              path: ""
        #              username: "{{ es_username }}"
        #              password: "{{ es_password }}"
        #            dashboards:
        #              enabled: true
        default_ilm_policy: ilm_policy.json
        output_conf:
          elasticsearch:
            hosts: "{{ output_elasticsearch_url }}"
            protocol: "https"
            username: "{{ es_username }}"
            password: "{{ es_password }}"
            ssl:
              verification_mode: "certificate"
              certificate_authorities:
                - "{{ certs_path }}"
        logging_conf:
          level: info
          json: true
          to_files: true
          files:
            path: /var/log/metricbeat
            name: metricbeat.log
            keepfiles: 7
            permissions: 0644
            rotateeverybytes: 31457280
