---
ca_path: "{{ playbook_dir }}/certificates/ca/ca.crt"
metricbeat_module:
  module: kibana
  metricsets:
    - status
  period: 10s
  hosts: [ "https://{{ ansible_eth1.ipv4.address }}:5601" ]
  username: "{{ es_username }}"
  password: "{{ es_password }}"
  basepath: ""
  enabled: true
  xpack.enabled: true
  ssl:
    verification_mode: "certificate"
    certificate_authorities:
      - "{{ certs_path }}"