---
- name: Prerequisite for kibna installation
  tags: [ "kibana_users","install_kibana" ]
  block:
    - name: Setup Users and Directories for Kibana
      include_tasks: users.yml

- name: Add Kibana Certificates
  become: yes
  tags: [ "copy-certs","install-kibana" ]
  copy:
    dest: "{{ kibana_certs_path }}/"
    src: "{{ item }}"
    owner: kibana
    group: kibana
    mode: 0444
  with_items:
    - "{{ kibana_ssl_certificate_authority }}"
    - "{{ kibana_ssl_certificate }}"
    - "{{ kibana_ssl_key }}"

- name: Install and Configure Kibana
  become: yes
  tags: [ "install_kibana" ]
  block:
    - include_role:
        name: ansible-kibana
      vars:
        kibana_version: "7.x"
        kibana_package: kibana-7.12.1
        kibana_package_state: present
        kibana_elasticsearch_url: "https://10.0.0.10:9200"
        kibana_elasticsearch_username: "elastic"
        kibana_elasticsearch_password: "passowrd@123"
        kibana_config_template: "kibana-custom.yml.j2"